#!/bin/sh

usage() {
  echo "
    Usage:
    kubedeps [child_process_cmd]

    child_process_cmd:  any executable command with its argments, as a single string
                        e.g. \"sh -c 'ls -la'\"

    environment variables:
      KUBEDEPS_POLLING_INTERVAL
        e.g. 30
        default to 10
        used to determine the number of seconds between each check (birth and death)
      KUBEDEPS_NAME
        e.g. my_process_name
        required
        the name of the kubedeps process and will be the filename of the tombstone, this is the name that should be refered to in birth and death deps
      KUBEDEPS_GRAVEYARD
        e.g. /graveyard
        required
        the path of the kubedeps graveyard
      KUBEDEPS_BIRTH_DEPS
        e.g. deps1,deps2
        default to none (empty string)
        list of comma separated birth deps (corresponding to KUBEDEPS_NAME of the deps). Note that birth deps will be fulfilled once all the birth deps are in ready state (not just born).
      KUBEDEPS_BIRTH_TIMEOUT
        e.g. 15
        default to 30
        number of seconds before considering that process birth wait timed out
      KUBEDEPS_DEATH_DEPS
        e.g. deps3,deps4
        default to none (empty string)
        list of comma separated death deps (corresponding to KUBEDEPS_NAME of the deps)
      KUBEDEPS_GRACE_PERIOD
        e.g. 45
        default to 30
        grace period for the child process to exit before exiting the kubedeps process, note that we will not force kill the child process but just exit
      KUBEDEPS_READY_CMD
        e.g. ls
        default to none (empty string)
        command exiting with 0 when process is ready or else with a non-zero exit code
      KUBEDEPS_READY_INTERVAL
        e.g. 10
        default to 5
        number of seconds between each KUBEDEPS_READY_CMD invocation
      KUBEDEPS_READY_TIMEOUT
        e.g. 60
        default to 30
        number of seconds before considering that the child process failed to start
      KUBEDEPS_EXIT_CODE
        e.g. 0
        default to none, will use the child process exit code
        exit code used by the kubedeps process
      KUBEDEPS_DISABLE_LOGGING
        if this variable is set, kubedeps will do less verbose logging, e.g. not log the config at startup
  "
}

if [ -z "${KUBEDEPS_NAME}" ]; then
  echo "[error]     KUBEDEPS_NAME must be defined"
  usage
  exit 1
elif [ -z "${KUBEDEPS_GRAVEYARD}" ]; then
  echo "[error]    KUBEDEPS_GRAVEYARD must be defined"
  usage
  exit 1
elif [ ! -z "${KUBEDEPS_GRAVEYARD}" ] && [ ! -d "${KUBEDEPS_GRAVEYARD}" ]; then
  echo "[error]     KUBEDEPS_GRAVEYARD doesn't exist or is not a folder"
  usage
  exit 1
elif [ "${#}" -eq 0 ]; then
  echo "[error]     no child process to execute"
  usage
  exit 1
fi

log() {
  if [ -z "${KUBEDEPS_DISABLE_LOGGING}" ];
  then echo $1;
  fi
}

NAME=${KUBEDEPS_NAME}
GRAVEYARD=${KUBEDEPS_GRAVEYARD}
CHILD_CMD="${*}"

BIRTH_DEPS=${KUBEDEPS_BIRTH_DEPS}
BIRTH_TIMEOUT=${KUBEDEPS_BIRTH_TIMEOUT=30}

DEATH_DEPS=${KUBEDEPS_DEATH_DEPS}
GRACE_PERIOD=${KUBEDEPS_GRACE_PERIOD=30}

READY_CMD=${KUBEDEPS_READY_CMD}
READY_INTERVAL=${KUBEDEPS_READY_INTERVAL=5}
READY_TIMEOUT=${KUBEDEPS_READY_TIMEOUT=30}

POLLING_INTERVAL=${KUBEDEPS_POLLING_INTERVAL=10}

EXIT_CODE=${KUBEDEPS_EXIT_CODE}

###
## Runtime values
###

KUBEDEPS_PID=$$
CHILD_PID=
DEATH_WATCHER_PID=
BIRTH_WATCHER_PID=
READINESS_WATCHER_PID=
CHILD_EXIT_CODE=

###
## Print values on startup
###

log "
--------
  Starting kubedeps with values
  
  command: ${CHILD_CMD}
  KUBEDEPS_NAME=${NAME}
  KUBEDEPS_GRAVEYARD=${GRAVEYARD}
  KUBEDEPS_BIRTH_DEPS=${BIRTH_DEPS}
  KUBEDEPS_BIRTH_TIMEOUT=${BIRTH_TIMEOUT=30}
  KUBEDEPS_DEATH_DEPS=${DEATH_DEPS}
  KUBEDEPS_GRACE_PERIOD=${GRACE_PERIOD}
  KUBEDEPS_READY_CMD=${READY_CMD}
  KUBEDEPS_READY_INTERVAL=${READY_INTERVAL=5}
  KUBEDEPS_READY_TIMEOUT=${READY_TIMEOUT=30}
  KUBEDEPS_POLLING_INTERVAL=${POLLING_INTERVAL=10}
--------
"

###
## Utility functions
###

get_own_pid() {
  cut -d' ' -f4 < /proc/self/stat \
    | xargs -I% sh -c 'cut -d" " -f4 < /proc/%/stat'
}

get_parent_pid() {
  cut -d' ' -f4 < /proc/self/stat \
    | xargs -I% sh -c 'cut -d" " -f4 < /proc/%/stat' \
    | xargs -I% sh -c 'cut -d" " -f4 < /proc/%/stat'
}

timeout_for()
{
    remove_timer() {
      trap - EXIT
      kill -9 "${SLEEP_PID}" > /dev/null 2>&1
      exit 0
    }
    trap "remove_timer" ALRM
    trap "remove_timer" EXIT

    sleep "${1}"& SLEEP_PID=$!
    wait
    TIMEOUT_PARENT_PID=$(get_parent_pid)
    kill -ALRM "${TIMEOUT_PARENT_PID}"
}

###
## Defining functions
###

carve_tombstone() {
  if [ -z "${1}" ] && [ -f "${GRAVEYARD}/${NAME}" ]; then
    echo "[error]      conflict, ${GRAVEYARD}/${NAME} already exists"
    exit 2
  elif [ -z "${1}" ]; then
    log "[tombstone]  Creating tombstone at ${GRAVEYARD}/${NAME}"
    log 'birth:' > "${GRAVEYARD}/${NAME}"
    log 'ready:' >> "${GRAVEYARD}/${NAME}"
    log 'death:' >> "${GRAVEYARD}/${NAME}"
  elif [ ! -w "${GRAVEYARD}/${NAME}" ]; then
    echo "[error]      ${GRAVEYARD}/${NAME} is not found or is not writable"
    exit 3
  elif [ ! -z "${1}" ] && [ -w "${GRAVEYARD}/${NAME}" ]; then
    log "[tombstone]  Carving ${1} on tombstone at ${GRAVEYARD}/${NAME}"
    if ! grep -q -e "^${1}:$" "${GRAVEYARD}/${NAME}"; then
      echo "[error]      conflict, ${1} already carved on ${GRAVEYARD}/${NAME}"
      exit 4
    fi

    sed -i "s/^${1}:$/${1}: $(date -Ins -u)/g" "${GRAVEYARD}/${NAME}"
  fi
}

# Kill all the descendant processes before exiting
# Allow a grace period for a graceful shutdown
clean_exit() {
  # Kill watchers if they exists
  kill -TERM "${BIRTH_WATCHER_PID}" "${DEATH_WATCHER_PID}" "${READINESS_WATCHER_PID}" > /dev/null 2>&1
  # Clean signal trap for EXIT
  trap - EXIT

  log "[main]       Process exit started."

  # If the child process was started, bring it down gracefully or
  # forcefully if timeout is exceeded
  if [ ! -z "${CHILD_PID}" ] && [ -z "${CHILD_EXIT_CODE}" ]; then
    # This function will be called if the child process is still alive after grace period
    exit_after_grace_period_timeout() {
      # Clean signal trap for ALRM
      trap - ALRM
      log "[watcher]    Children grace period timed out"
      carve_tombstone death
      # Exit with error code because child was forced exit
      exit 5
    }
    trap "exit_after_grace_period_timeout" ALRM

    # Sending SIGTERM to child process, allowwing for graceful shutdown
    kill -TERM "${CHILD_PID}" > /dev/null 2>&1
    log "[watcher]    Waiting for graceful shutdown or timeout (${GRACE_PERIOD}s)"
    # Launching a timeout process in the background and store its PID in TIMEOUT_PROCESS_PID
    timeout_for ${GRACE_PERIOD}& TIMEOUT_PROCESS_PID=$!
    # Wait for child process to exit
    wait "${CHILD_PID}"
    CHILD_EXIT_CODE="${?}"
    log "[status]     Child exited with code: ${CHILD_EXIT_CODE}"
    carve_tombstone death
    # If child process did exit before timeout, stop the timeout process
    kill -ALRM "${TIMEOUT_PROCESS_PID}"
    log "[main]       Graceful shutdown done."
  elif [ ! -z "${CHILD_EXIT_CODE}" ]; then
    carve_tombstone death
  elif [ -z "${CHILD_PID}" ]; then
    log "[main]       Child was never started, exiting."
    carve_tombstone death
    exit 6
  fi

  log "[main]       Done."
  if [ ! -z "${EXIT_CODE}" ]; then
    exit "${EXIT_CODE}"
  elif [ ! -z "${CHILD_EXIT_CODE}" ]; then
    exit "${CHILD_EXIT_CODE}"
  fi

  exit 0
}

is_event_fulfilled() {
  FILE_TO_CHECK="${1}"
  EVENT_TO_CHECK="${2}"

  # Check if this specific dep fulfilled the event, return no if it didn't or yes if it did
  if [ ! -f "${WAIT_FOR_FILE}" ] || ! grep -q -E "^${EVENT_TO_CHECK}: .+" "${FILE_TO_CHECK}"; then
    log no
    exit
  fi

  log yes
}

wait_for() {
  # Get event and files from arguments
  WAIT_FOR_EVENT="${2}"
  WAIT_FOR_FILES=$(echo "${1}" | tr ',' ' ')

  log "[watcher]    > Waiting for ${1} to fulfill event: ${WAIT_FOR_EVENT}"
  # Loop until event are fulfilled
  while true; do
    # For every deps, check if the event is fulfilled
    for file in ${WAIT_FOR_FILES}; do
      WAIT_FOR_FILE="${GRAVEYARD}/${file}"
      IS_FULFILLED=$(is_event_fulfilled "${WAIT_FOR_FILE}" "${WAIT_FOR_EVENT}")

      # Early break the loop on the first unfulfilled event
      if [ "${IS_FULFILLED}" = "no" ]; then
        break
      fi
    done

    # If the loop ended on an unfulfilled event, wait and retry,
    # else all the events are fulfilled, then break the infinity loop and exit watcher
    if [ "${IS_FULFILLED}" = "no" ]; then
      sleep "${POLLING_INTERVAL}"
    else
      log "[watcher]    > Events fulfilled"
      break
    fi
  done
}

# This function must be launched as a background process
wait_for_deps_event() {
  WAIT_FOR_DEPS="${1}"
  WAIT_FOR_DEPS_EVENT="${2}"
  WAIT_FOR_DEPS_TIEMOUT="${3}"

  if [ ! -z "${WAIT_FOR_DEPS_TIEMOUT}" ]; then
    # If timeout is reached, kill watcher and exit
    wait_for_deps_event_timeout_reached() {
      echo "[error]      timeout reached before deps conditions were fulfilled (${WAIT_FOR_DEPS}: ${WAIT_FOR_DEPS_EVENT})"
      # When this function exit because the timeout was reached, return an error code
      exit 1
    }
    trap "wait_for_deps_event_timeout_reached" ALRM
    wait_for_deps_event_before_exit() {
      kill -TERM "${WATCHER_WATCHER_PID}" "${WATCHER_TIMEOUT_PID}" > /dev/null 2>&1
    }
    trap "wait_for_deps_event_before_exit" EXIT

    # Start watching for event and start timeout countdown
    wait_for "${WAIT_FOR_DEPS}" "${WAIT_FOR_DEPS_EVENT}"& WATCHER_WATCHER_PID=$!
    timeout_for "${WAIT_FOR_DEPS_TIEMOUT}"& WATCHER_TIMEOUT_PID=$!
    # Wait for watcher to complete successfully
    wait "${WATCHER_WATCHER_PID}"
    exit
  else
    wait_for "${WAIT_FOR_DEPS}" "${WAIT_FOR_DEPS_EVENT}"
  fi
}

watch_for_death_deps() {
  watch_for_death_deps_before_exit() {
    kill -TERM "${WAIT_FOR_DEATH_DEPS}" > /dev/null 2>&1
  }
  trap "watch_for_death_deps_before_exit" EXIT

  wait_for_deps_event "${DEATH_DEPS}" death& WAIT_FOR_DEATH_DEPS=$!
  wait "${WAIT_FOR_DEATH_DEPS}"
  log "[watcher]    > Death dependecies are met"
  kill -TERM "${KUBEDEPS_PID}"
}

watch_for_birth_deps() {
  watch_for_birth_deps_before_exit() {
    kill -TERM "${WAIT_FOR_BIRTH_DEPS}" > /dev/null 2>&1
  }
  trap "watch_for_birth_deps_before_exit" EXIT

  wait_for_deps_event "${BIRTH_DEPS}" ready "${BIRTH_TIMEOUT}"& WAIT_FOR_BIRTH_DEPS=$!
  wait "${WAIT_FOR_BIRTH_DEPS}"
  WAIT_FOR_BIRTH_DEPS_EXIT_CODE="${?}"

  # If birth deps reached timeout, we kill the main process
  if [ "${WAIT_FOR_BIRTH_DEPS_EXIT_CODE}" -ne 0 ]; then
    kill -TERM "${KUBEDEPS_PID}"
  else
    log "[watcher]    > Birth dependecies are met"
  fi
}

watch_for_readiness() {
  watch_for_readiness_before_exit() {
    trap - EXIT
    kill -TERM "${WAIT_FOR_READINESS_TIMEOUT_PID}" "${WAIT_FOR_READINESS_SLEEP_PID}" > /dev/null 2>&1
  }
  trap "watch_for_readiness_before_exit" EXIT
  watch_for_readiness_timeout_reached() {
    echo "[error]      timeout reached while waiting for child process to be ready"
    kill -TERM "${KUBEDEPS_PID}"
  }
  trap "watch_for_readiness_timeout_reached" ALRM

  timeout_for "${READY_TIMEOUT}"& WAIT_FOR_READINESS_TIMEOUT_PID=$!
  while ! sh -c "${READY_CMD} > /dev/null 2>&1"
  do
    log "> Waiting for child process to be ready"
    sleep "${READY_INTERVAL}"& WAIT_FOR_READINESS_SLEEP_PID=$!
    wait "${WAIT_FOR_READINESS_SLEEP_PID}"
  done;
}

###
## Run the script
###

# Catch exit and execute clean_exit function
trap "clean_exit" EXIT
trap "clean_exit" TERM

# Initialise an empty tombstone
carve_tombstone

# If death deps are passed, watch for them and this will kill the whole process
# if they are met
if [ ! -z "${DEATH_DEPS}" ]; then
  watch_for_death_deps& DEATH_WATCHER_PID=$!
fi

# If birth deps are passed, watch for them and continue once fulfilled
if [ ! -z "${BIRTH_DEPS}" ]; then
  watch_for_birth_deps& BIRTH_WATCHER_PID=$!
  wait "${BIRTH_WATCHER_PID}"
fi

# Launch child process
"${@}"& CHILD_PID=$!
log "[status]     alive (pid: ${CHILD_PID})"
carve_tombstone birth

# If readiness command is given, wait for readiness
if [ ! -z "${READY_CMD}" ]; then
  watch_for_readiness& READINESS_WATCHER_PID=$!
  wait "${READINESS_WATCHER_PID}"
fi
log "[status]     ready"
carve_tombstone ready

wait "${CHILD_PID}"
CHILD_EXIT_CODE="${?}"
log "[status]     Child exited with code: ${CHILD_EXIT_CODE}"
